COPY website_parcel (objectid,
                     parcelid,
                     kivapin,
                     address,
                     subdivision,
                     block,
                     lot,
                     datecreated,
                     landusecode,
                     apn,
                     parceltype,
                     status,
                     condo,
                     platname,
                     fraction,
                     prefix,
                     suite,
                     own_name,
                     own_addr,
                     own_city,
                     own_zip,
                     blvdfront,
                     lastupdate,
                     shape_length,
                     shape_area,
                     latitude,
                     longitude,
                     location1) from '/home/aaron/parcel_data_small.csv' DELIMITER ',' CSV HEADER;
