SELECT
  wv.property_violation_id   AS wv_property_violation_id,
  wv.case_id                 AS wv_case_id,
  wv.status                  AS wv_status,
  wv.case_opened             AS wv_case_closed,
  wv.days_open               AS wv_days_open,
  wv.violation_code          AS wv_violation_code,
  wv.violation_description   AS wv_violation_description,
  wv.ordinance_number        AS wv_ordinance_number,
  wv.ordinance_chapter       AS wv_ordinance_chapter,
  wv.violation_entry_date    AS wv_violation_entry_date,
  wv.address                 AS wv_address,
  wv.county                  AS wv_county,
  wv.state                   AS wv_state,
  wv.zip_code                AS wv_zip_code,
  wv.latitude                AS wv_latitude,
  wv.longitude               AS wv_longitude,
  wv.council_district        AS wv_council_district,
  wv.police_patrol           AS wv_police_patrol,
  wv.inspection_area         AS wv_inspection_area,
  wv.neighborhood            AS wv_neighborhood,
  wv.code_violation_location AS wv_code_violation_location,
  wv.kivapin                 AS wv_kviapin,
  wp.objectid                AS wp_object_id,
  wp.parcelid                AS wp_parcel_id,
  wp.kivapin                 AS wp_kivapin,
  wp.address                 AS wp_address,
  wp.subdivision             AS wp_subdivision,
  wp.block                   AS wp_block,
  wp.lot                     AS wp_lot,
  wp.datecreated             AS wp_datecreated,
  wp.landusecode             AS wp_landusecode,
  wp.apn                     AS wp_apn,
  wp.parceltype              AS wp_parceltype,
  wp.status                  AS wp_status,
  wp.condo                   AS wp_condo,
  wp.platname                AS wp_platname,
  wp.fraction                AS wp_fraction,
  wp.prefix                  AS wp_prefix,
  wp.suite                   AS wp_suite,
  wp.own_name                AS wp_own_name,
  wp.own_addr                AS wp_own_addr,
  wp.own_city                AS wp_own_city,
  wp.own_zip                 AS wp_own_zip,
  wp.own_state               AS wp_own_state,
  wp.blvdfront               AS wp_blvdfront,
  wp.lastupdate              AS wp_lastupdate,
  wp.shape_length            AS wp_shape_length,
  wp.shape_area              AS wp_shape_area,
  wp.latitude                AS wp_latitude,
  wp.longitude               AS wp_longitude,
  wp.location1               AS wp_location1


FROM website_violation wv
  INNER JOIN website_parcel wp
    ON (wv.kivapin = wp.kivapin)
       AND wv.county = 'Jackson'
       AND wv.status = 'Open';