from django.db import models


# Create your models here.
class Parcel(models.Model):
    objectid = models.TextField(null=True, blank=True)
    parcelid = models.TextField(null=True, blank=True)
    kivapin = models.TextField(null=True, blank=True)
    subdivision = models.TextField(null=True, blank=True)
    block = models.TextField(null=True, blank=True)
    lot = models.TextField(null=True, blank=True)
    datecreated = models.TextField(null=True, blank=True)
    landusecode = models.TextField(null=True, blank=True)
    apn = models.TextField(null=True, blank=True)
    parceltype = models.TextField(null=True, blank=True)
    status = models.TextField(null=True, blank=True)
    condo = models.TextField(null=True, blank=True)
    platname = models.TextField(null=True, blank=True)
    fraction = models.TextField(null=True, blank=True)
    prefix = models.TextField(null=True, blank=True)
    suite = models.TextField(null=True, blank=True)
    own_name = models.TextField(null=True, blank=True)
    own_addr = models.TextField(null=True, blank=True)
    own_city = models.TextField(null=True, blank=True)
    own_zip = models.TextField(null=True, blank=True)
    blvdfront = models.TextField(null=True, blank=True)
    lastupdate = models.TextField(null=True, blank=True)
    shape_length = models.TextField(null=True, blank=True)
    shape_area = models.TextField(null=True, blank=True)
    latitude = models.TextField(null=True, blank=True)
    longitude = models.TextField(null=True, blank=True)
    location1 = models.TextField(null=True, blank=True)


class Violation(models.Model):
    property_violation_id = models.TextField(null=True, blank=True)
    case_id = models.TextField(null=True, blank=True)
    status = models.TextField(null=True, blank=True)
    case_opened = models.TextField(null=True, blank=True)
    case_closed = models.TextField(null=True, blank=True)
    days_open = models.TextField(null=True, blank=True)
    violation_code = models.TextField(null=True, blank=True)
    violation_description = models.TextField(null=True, blank=True)
    ordinance_number = models.TextField(null=True, blank=True)
    ordinance_chapter = models.TextField(null=True, blank=True)
    violation_entry_date = models.TextField(null=True, blank=True)
    address = models.TextField(null=True, blank=True)
    county = models.TextField(null=True, blank=True)
    state = models.TextField(null=True, blank=True)
    zip_code = models.TextField(null=True, blank=True)
    latitude = models.TextField(null=True, blank=True)
    longitude = models.TextField(null=True, blank=True)
    kiva_pin = models.TextField(null=True, blank=True)
    council_district = models.TextField(null=True, blank=True)
    police_patrol = models.TextField(null=True, blank=True)
    inspection_area = models.TextField(null=True, blank=True)
    neighborhood = models.TextField(null=True, blank=True)
    code_violation_location = models.TextField(null=True, blank=True)
